// Generates Source/DSP/CompTableData.h (the level-compensation table used by Drive).
// Run it whenever Source/DSP/SaturatorCore.h changes:
//   g++ -std=c++17 -O2 Tools/GenCompTable.cpp -o gen && ./gen > Source/DSP/CompTableData.h
#include "../Source/DSP/SaturatorCore.h"
#include <cstdio>

int main()
{
    using namespace nfsat;
    std::printf("// GENERATED by Tools/GenCompTable.cpp -- do not edit. Compensation in dB, [tube][iron][solid][drive].\n");
    std::printf("// Valve axis: 0..4 = warmth 0, .25, .5, .75, 1 (valve on); 5 = valve off. Drive axis: 21 steps 0..10.\n");
    std::printf("#pragma once\nnamespace nfsat\n{\ninline constexpr float kCompDb[6][6][6][21] = {\n");
    for (int t = 0; t < 6; ++t) { std::printf("{\n");
        for (int i = 0; i < 6; ++i) { std::printf("{\n");
            for (int s = 0; s < 6; ++s) { std::printf("{");
                Stages st;
                st.tube = t < 5; st.iron = i < 5; st.solid = s < 5;
                st.tubeAmt = t < 5 ? t * 0.25 : 0.0; st.ironAmt = i < 5 ? i * 0.25 : 0.0; st.solidAmt = s < 5 ? s * 0.25 : 0.0;
                for (int d = 0; d < 21; ++d)
                    std::printf("%s%.3ff", d ? "," : "", measureCompensationDb(kMaxDrive * d / 20.0, st));
                std::printf("}%s\n", s < 5 ? "," : ""); }
            std::printf("}%s\n", i < 5 ? "," : ""); }
        std::printf("}%s\n", t < 5 ? "," : ""); }
    std::printf("};\n}\n");
}
