#pragma once
#include "SaturatorCore.h"
#include "CompTableData.h"   // generated by Tools/GenCompTable.cpp -- regenerate whenever SaturatorCore.h changes

namespace nfsat
{
// Table axes: for each valve 0..4 = warmth 0, .25, .5, .75, 1 (valve on) and 5 = valve off; last axis = Drive in 21 steps.
constexpr int kAmtLevels = 5, kValveIdx = 6, kDriveSteps = 21;

// Level-compensation gain (linear) for Drive + valve states, interpolated in dB.
inline double compensationGain(double drive, const Stages& st)
{
    int i0[3], i1[3]; double f[3];
    const bool on[3] = { st.tube, st.iron, st.solid };
    const double amt[3] = { st.tubeAmt, st.ironAmt, st.solidAmt };
    for (int v = 0; v < 3; ++v)
    {
        if (!on[v]) { i0[v] = i1[v] = kAmtLevels; f[v] = 0.0; continue; }
        const double pos = std::clamp(amt[v], 0.0, 1.0) * (kAmtLevels - 1);
        i0[v] = std::min((int) pos, kAmtLevels - 2); i1[v] = i0[v] + 1; f[v] = pos - i0[v];
    }
    const double dpos = std::clamp(drive, 0.0, kMaxDrive) / kMaxDrive * (kDriveSteps - 1);
    const int d0 = std::min((int) dpos, kDriveSteps - 2); const double df = dpos - d0;
    double db = 0.0;
    for (int c = 0; c < 8; ++c)
    {
        const int a = (c & 1) ? i1[0] : i0[0], b = (c & 2) ? i1[1] : i0[1], d = (c & 4) ? i1[2] : i0[2];
        const double w = ((c & 1) ? f[0] : 1.0 - f[0]) * ((c & 2) ? f[1] : 1.0 - f[1]) * ((c & 4) ? f[2] : 1.0 - f[2]);
        if (w <= 0.0) continue;
        db += w * ((1.0 - df) * kCompDb[a][b][d][d0] + df * kCompDb[a][b][d][d0 + 1]);
    }
    return std::pow(10.0, db / 20.0);
}
}
